//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSalon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Visits = new HashSet<Visit>();
        }
    
        public int CustomerID { get; set; }

        [Required]
        [Display(Name = "Vorname")]
        public string FName { get; set; }
        [Required]
        [Display(Name = "Nachname")]
        public string LName { get; set; }
        [Display(Name = "Geburstag")]
        public Nullable<System.DateTime> BirthDay { get; set; }
        [Display(Name = "WeiblichJN")]
        public Nullable<bool> Female { get; set; }
        [Display(Name = "Notizen")]
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visits { get; set; }

        public virtual List<Visit> CustomerVisits { get; set; }
    }
}
