//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitsTreatment
    {
        public int VisitsID { get; set; }
        public int TreatmentsID { get; set; }
        public int OrderID { get; set; }
    
        public virtual Treatment Treatment { get; set; }
        public virtual Visit Visit { get; set; }
    }
}
